spring:
  application:
    name: ropa-inventory-service
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
