spring:
  application:
    name: consent-service
  datasource:
    url: ${spring.datasource.url:jdbc:postgresql://localhost:5432/consent}
    hikari:
      connection-init-sql: SET search_path TO consent
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: consent
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: consent

audit:
  schema: consent

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

